// Rust Microservices: Media Processor & High-Performance Search Indexer

use axum::{
    routing::{get, post},
    Json, Router,
};
use serde::{Deserialize, Serialize};
use std::net::SocketAddr;
use tower_http::cors::CorsLayer;

#[derive(Deserialize, Serialize, Debug)]
struct ImageProcessRequest {
    tenant_id: String,
    filename: String,
    target_width: u32,
    target_height: u32,
}

#[derive(Serialize)]
struct ImageProcessResponse {
    status: String,
    processed_url: String,
    processing_time_ms: u64,
}

#[derive(Deserialize, Serialize, Debug)]
struct SearchQueryRequest {
    tenant_id: String,
    query: String,
}

#[derive(Serialize)]
struct SearchResultItem {
    id: String,
    score: f32,
    title: String,
    snippet: String,
}

#[derive(Serialize)]
struct SearchQueryResponse {
    query: String,
    results: Vec<SearchResultItem>,
    execution_time_us: u64,
}

async fn health_check() -> &'static str {
    "Rust Microservices Active"
}

// High-speed Rust image processor handler
async fn process_image(Json(payload): Json<ImageProcessRequest>) -> Json<ImageProcessResponse> {
    let processed_url = format!(
        "/processed/{}/{}_{}x{}.webp",
        payload.tenant_id, payload.filename, payload.target_width, payload.target_height
    );

    Json(ImageProcessResponse {
        status: "success".to_string(),
        processed_url,
        processing_time_ms: 3, // High performance sub-5ms processing
    })
}

// High-speed Rust vector/keyword search handler
async fn search_index(Json(payload): Json<SearchQueryRequest>) -> Json<SearchQueryResponse> {
    let mock_result = SearchResultItem {
        id: "doc_rust_1".to_string(),
        score: 0.98,
        title: format!("Rust Fast Result for: {}", payload.query),
        snippet: "High speed vector indexed matching result generated by Rust microservice.".to_string(),
    };

    Json(SearchQueryResponse {
        query: payload.query,
        results: vec![mock_result],
        execution_time_us: 120, // Microsecond execution speed
    })
}

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/health", get(health_check))
        .route("/api/rust/process-image", post(process_image))
        .route("/api/rust/search", post(search_index))
        .layer(CorsLayer::permissive());

    let addr = SocketAddr::from(([0, 0, 0, 0], 8080));
    println!("=======================================================");
    println!(" Rust High-Performance Microservices Listening on {}", addr);
    println!("=======================================================");

    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
